= Deployment Instructions and Playbooks for Novello System

== Obtaining Files

Go to xxx to get the files

== Customizing Classroom

Run XXX playbook to customize the classroom.


== Testing Process for Satellite

.Configure RHV Environment for Networking and Storage (Development DC)
[source,bash]
----
[student@workstation ~]$ lab vms-install start
----


.Configure RHV Environment for Networking and Storage (Production DC)
[source,bash]
----
[student@workstation ~]$ lab vms-review start
----

=== Testing Exercises

. Chapter 14 (GE - Setup Remote Execution)
+
.Ansible Playbook can complete this
[TIP]
====
[source,bash]
----
[student@workstation Ansible]$ ansible-playbook CH14-ge-remote-execution.yml
----
====
. Chapter 15 (GEs)
.. Configure Ansible Remote Execution
+
[source,bash]
----
[root@satellite ~]# wget http://materials/Sat6_Files/ansible-role.tgz

[root@satellite ~]# tar xzvf ansible-role.tgz

[root@satellite ~]# mkdir -p /etc/ansible/roles/motd/tasks

[root@satellite ~]# mkdir -p /etc/ansible/roles/motd/templates

[root@satellite ~]# cp main.yaml /etc/ansible/roles/motd/tasks

[root@satellite ~]# cp motd.j2 /etc/ansible/roles/motd/templates

----
+
.Ansible Playbook can complete this
[TIP]
====
[source,bash]
----
[student@workstation Ansible]$ ansible-playbook CH15-ge-ansible-remote-execution.yml
----
====
.. Automating Registration of Content Hosts
+
[source,bash]
----
[student@workstation Ansible]$ ansible-playbook CH15-ge-activation-key.yml
----

. Chapter 16 (GE - Creating a Red Hat Virtualization Compute Resource in Satellite)
.. Refer to CH16 hammer notes
+
.Source Description
[source,bash]
----
hammer compute-resource create \
--name "RHV Production Datacenter" --provider "Ovirt" \
--description "Compute Resource for Production Data Center" \
--url "https://rhvm.lab.example.com/ovirt-engine/api" \
--use-v4 "false" --user "admin@internal" \
--password "redhat" \
--locations "Boston" --organizations "Operations" \
--datacenter "production"



hammer compute-resource create \
--name "RHV Development Datacenter" --provider "Ovirt" \
--description "Compute Resource for Development Data Center" \
--url "https://rhvm.lab.example.com/ovirt-engine/api" \
--use-v4 "false" --user "admin@internal" \
--password "redhat" \
--locations "Boston" --organizations "Operations" \
--datacenter "development"
----
+
.Can be completed with Ansible Playbook
[TIP]
====
[source,bash]
----
[student@workstation Ansible]$ ansible-playbook CH16-create-compute-resource.yml
----
====

. Chapter 17 (GEs)
.. Configuring Satellite Server for Host Provisioning
+
.Setup Kickstart Trees
[source,bash]
----
[student@workstation Ansible]$ ansible-playbook CH17-configure-network-kickstart.yml


----
.. Preparing Network Configuration for Provisioning
+
.Lab Start Script
[source,bash]
----
[student@workstation ~]$ lab sat6-net-prov start
----
+
.Configuring Network Resources
[source,bash]
----
satellite-installer --foreman-proxy-dns true \
--foreman-proxy-dns-interface eth0 \
--foreman-proxy-dns-forwarders 172.25.250.254 \
--foreman-proxy-dns-zone boston.lab.example.com \
--foreman-proxy-dns-reverse 250.25.172.in-addr.arpa \
--foreman-proxy-dhcp true \
--foreman-proxy-dhcp-interface eth0 \
--foreman-proxy-dhcp-range "172.25.250.50 172.25.250.100" \
--foreman-proxy-dhcp-nameservers 172.25.250.15 \
--foreman-proxy-dhcp-gateway 172.25.250.254 \
--foreman-proxy-tftp true
----
+
.Replaces need for Bash script
[TIP]
====
The following playbook will create the Satellite Installer resources, Configure the Boston Domain, and Setup the Boston subnet

[source,bash]
----
[student@workstation Ansible]$ ansible-playbook CH17-configure-network-provisioning.yml
----

====
+
.Lab Finish Script
[source,bash]
----
[student@workstation ~]$ lab sat6-net-prov finish
----
. Chapter 17 (GE - Performing Host Provisioning with RHV and Satellite)
+
.Creation of Hostgroup and Settings/Activation Key
[source,bash]
----
[student@workstation Ansible]$ ansible-playbook CH18-configure-host.yml
----


.Warning Header
[WARNING]
====
Notes:

hammer host create --name "hammer-test" --hostgroup "Operations Virtual Host Group" --provision-method build --build true --enabled true --managed true --interface "managed=true,primary=true,provision=true,compute_name=eth0,compute_network=ovirtmgmt" --compute-attributes="cluster=clustertwo,template=Blank,cores=2,memory=2048M,start=true" --volume="size_gb=20G,storage_domain=nfs-data,bootable=true" --root-password redhat123 --organization "Operations" --location "Boston" --medium "Synced Content"
====
