---
- hosts: rhvm.lab.example.com
  user: root
  become: false
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml

  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  tasks:
    - name: Put HostB into Maintenance Mode
      ovirt_host:
        name: hostb.lab.example.com
        auth: "{{ ovirt_auth }}"
        state: maintenance

    - name: Remove HostB from Cluster
      ovirt_host:
        name: hostb.lab.example.com
        auth: "{{ ovirt_auth }}"
        state: absent

    - name: Pause for Maintenance Mode
      pause:
        seconds: 45

    - name: Move HostB into Development DC and ClusterOne
      ovirt_host:
        name: hostb.lab.example.com
        auth: "{{ ovirt_auth }}"
        cluster: clusterone
        state: present
        password: "{{ engine_password }}"
        public_key: true
        address: hostb.lab.example.com
        force: true

    - name: Put HostC into Maintenance Mode
      ovirt_host:
        name: hostc.lab.example.com
        auth: "{{ ovirt_auth }}"
        state: maintenance

    - name: Remove HostC from Cluster
      ovirt_host:
        name: hostc.lab.example.com
        auth: "{{ ovirt_auth }}"
        state: absent

    - name: Pause for Maintenance Mode
      pause:
        seconds: 45

    - name: Move HostC into Production DC and ClusterTwo
      ovirt_host:
        name: hostc.lab.example.com
        auth: "{{ ovirt_auth }}"
        cluster: clustertwo
        state: present
        password: "{{ engine_password }}"
        public_key: true
        address: hostc.lab.example.com
        force: true

  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - alwaysovi
