---
- hosts: rhvm.lab.example.com
  user: root
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml

  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  vars:
    data_center_name: production
    cluster_name: clustertwo

  tasks:

    - name: Setup NFS Storage Data Domain
      ovirt_storage_domain:
        auth: "{{ ovirt_auth }}"
        data_center: "{{ data_center_name }}"
        host: hostc.lab.example.com
        nfs:
         address: 172.24.0.8
         path: /exports/data
         version: v4
        name: nfs-data
        domain_function: data
        comment: Production DataCenter NFS Data Domain
        description: Production DataCenter NFS Data
        state: present
        wipe_after_delete: no



  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - alwaysovi
