---
- name: Enable internet services
  hosts: webserver_lab
  become: yes
  tasks:

  - name: RHEL DVD Repo has been defined.
    get_url:
      url: "http://materials/rhv/playbook_multi/rhel_dvd.repo"
      dest: /etc/yum.repos.d/rhel_dvd.repo
      mode: 0644

  - name: latest version of all required packages installed
    yum:
      name:
        - firewalld
        - httpd
        - mariadb-server
        - php
        - php-mysqlnd
      state: latest

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: httpd enabled and running
    service:
     name: httpd
     enabled: true
     state: started

  - name: mariadb enabled and running
    service:
      name: mariadb
      enabled: true
      state: started

  - name: test php page is installed
    get_url:
      url: "http://materials/rhv/playbook_review/index.php"
      dest: /var/www/html/index.php
      mode: 0644

  - name: info php page is installed
    get_url:
      url: "http://materials/rhv/playbook_review/info.php"
      dest: /var/www/html/info.php
      mode: 0644

- name: Test internet web server
  hosts: localhost
  become: no
  tasks:

  - name: connect to internet web server
    uri:
      url: http://172.25.250.23
      status_code: 200
