---
- name: Deploy oVirt AAA IPA using role
  hosts: rhvm.lab.example.com

  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml
  vars:
    aaa_profile_type: ipa
    aaa_user: uid=rhvadmin,cn=users,cn=accounts,dc=lab,dc=example,dc=com
    aaa_password: redhat
    aaa_profile_name: lab.example.com
    aaa_ldap:
      - utility.lab.example.com
  roles:
    - ovirt-aaa-ldap
