---
- hosts: rhvm.lab.example.com
  user: root
  become: true
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml

  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  vars:
    data_center_name: production
    cluster_name: clustertwo

  tasks:

    - name: Setup VM Network
      ovirt_network:
        auth: "{{ ovirt_auth }}"
        data_center: "{{ data_center_name }}"
        name: prod-vm-net
        clusters:
         - name: "{{ cluster_name }}"
           assigned: true
           required: true
           display: false
           migration: false
           gluster: false
        comment: Network for VM LAB traffic
        description: VM LAB network
        vm_network: true
        state: present
        vlan_tag: 20

    - name: Setup Storage Network
      ovirt_network:
        auth: "{{ ovirt_auth }}"
        data_center: "{{ data_center_name }}"
        name: prod-storage
        clusters:
         - name: "{{ cluster_name }}"
           assigned: true
           required: true
           display: false
           migration: true
           gluster: false
        comment: Network for LAB storage traffic
        description: Storage Network LAB
        vm_network: false
        state: present

    - name: Setup RHV-H Host Network for VMs
      ovirt_host_network:
        auth: "{{ ovirt_auth }}"
        name: hostc.lab.example.com
        check: true
        save: true
        interface: eth0
        networks:
          - name: prod-vm-net
            boot_protocol: dhcp

    - name: Setup RHV-H Host Network for Storage
      ovirt_host_network:
        auth: "{{ ovirt_auth }}"
        name: hostc.lab.example.com
        check: true
        save: true
        interface: eth1
        networks:
          - name: prod-storage
            boot_protocol: static
            address: 172.24.0.12
            netmask: 255.255.255.0


  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - alwaysovi
